import * as yaml from 'yaml';

export function getNonce() {
	let text = '';
	const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
	for (let i = 0; i < 32; i++) {
		text += possible.charAt(Math.floor(Math.random() * possible.length));
	}
	return text;
}

export const yamlOpts: yaml.ParseOptions & yaml.DocumentOptions & yaml.SchemaOptions = {
	// lineCounter: new yaml.LineCounter(),
	customTags: [
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 0,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_RESET',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 1,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_DIRECT_JUMP',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 2,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_JUMP_TO_SCRIPT',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 3,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_03',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 4,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_04',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 5,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_SCRIPT_RETURN',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 6,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 7,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JNE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 8,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JG',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 9,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JGE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 10,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JL',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 11,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JLE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 12,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JZ',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 13,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!JNZ',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 14,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!Switch',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 16,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_10',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 17,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_11',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 18,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_12',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 19,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_13',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 20,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_14',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 21,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_15',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 22,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_16',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 23,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_17',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 26,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_1A',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 27,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_1B',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 28,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_1C',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 29,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_1D',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 30,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_1E',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 31,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_1F',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 32,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_20',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 33,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_21',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 34,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_22',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 35,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_23',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 36,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_24',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 37,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_25',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 45,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_2D',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 46,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_2E',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 47,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_2F',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 48,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_30',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 49,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_CHOICE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 50,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_MENU_CHOICE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 51,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_33',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 52,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_34',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 54,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_36',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 57,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_39',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 58,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_3A',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 59,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_3B',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 60,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_3C',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 66,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_42',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 67,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_43',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 68,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_PLAY_VOICE',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 69,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_TEXTBOX_DISPLAY',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 71,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_FREE_TEXT_OR_CHARNAME',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 72,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_48',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 73,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_CLEAR_SCREEN',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 74,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_WAIT',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 75,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_4B',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 76,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_4C',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 79,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_4F',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 81,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_51',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 89,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_59',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 90,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_5A',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 95,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_5F',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 104,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_68',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 105,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_69',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 106,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_6A',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 108,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_6C',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 110,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_6E',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 111,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_6F',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 113,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_71',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 114,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_72',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 116,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_74',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 117,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_75',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 119,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_CUSTOM_TIP_77',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 123,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_7B',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 130,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_82',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 131,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_83',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 133,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_DEBUG_PRINT',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 134,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_SPECIAL_TEXT',
		  },
		  {
			collection: 'map',
			identify: value => value instanceof Object && 'opcode' in value && value.opcode === 255,
			nodeClass: yaml.YAMLMap,
			default: false,
			tag: '!OP_Insert',
		  },
	]
};